{
  "Adlinks":":green_square:",
  "Codex":":green_square:",
  "Delta":":green_square:",
  "Fluxus":":green_square:",
  "Hydrogen":":green_square:",
  "Trigon":":green_square:",
  "Vegax":":green_square:",
  "HohoHub":":red_square:"
}
